apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-worker-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMQ__Host: "fcg-rabbitmq"
  RabbitMQ__Port: "5672"
  AWS_REGION: "us-east-1"
  AWS_DEFAULT_REGION: "us-east-1"