apiVersion: v1
kind: Secret
metadata:
  name: payments-worker-secret
  namespace: fcg
type: Opaque
stringData:
  RabbitMQ__Username: "<RABBITMQ_USERNAME>"
  RabbitMQ__Password: "<RABBITMQ_PASSWORD>"
  AWS_ACCESS_KEY_ID: "<AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<AWS_SECRET_ACCESS_KEY>"
  AWS_SESSION_TOKEN: "<AWS_SESSION_TOKEN>"
  AWS_SQS_QUEUE_URL: "<AWS_SQS_QUEUE_URL>"